// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Bulletpre
    {
        public const string BundleName = "BULLETPRE";
        public const string BULLET_1 = "BULLET_1";
    }
    public class Planepre
    {
        public const string BundleName = "PLANEPRE";
        public const string F10 = "F10";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "UICONNECT_PREFAB";
        public const string UICONNECT = "UICONNECT";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "UIMSG_PREFAB";
        public const string UIMSG = "UIMSG";
    }
}
